version: '3.3'

services:
  web:
    container_name: web
    build: ./backend
    # entrypoint: ["/entrypoint.sh"]
    # command: sh -c "python manage.py runserver 0.0.0.0:8000"
    # command: sh -c "gunicorn --bind 0.0.0.0:8000 cycrent.wsgi --workers=4"
    depends_on:
      - db
    # Maps port on the local machine to port on Docker image
    expose:
      - "8000"
    ports:
      - "8000:8000"
    # networks:
    #   - django-network
    volumes:
    # Copy changes made to the project to your image in real-time.
      - ./backend:/app/web
      - ./data/web:/vol/web
      # - ./tmp_mysqld/cycrent/mysqld:/run/mysqld
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=cycrent_db
      - DB_USER=root
      - DB_PASSWORD=trailking201
      - ALLOWED_HOSTS=0.0.0.0

  # nginx:
  #   build: nginx
  #   restart: always
  #   volumes:
  #     - ./backend:/app/web
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web
  #   networks:
  #     - django-network

  db:
    container_name: database
    image: mysql:8.0.29
    ports:
      - "30000:3306"
    environment:
      MYSQL_DATABASE: 'cycrent_db'
      # MYSQL_USER: 'root'
      # MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'trailking201'
    volumes:
      # том в которых будет храниться база данных
      # - ./db:/docker-entrypoint-initdb.d/:ro
      - ./cache/db:/var/lib/mysql
      # - ./tmp_mysqld/cycrent/mysqld:/var/run/mysqld

# networks:
#   django-network:
#     name: django-network